
spring:
  datasource:
    url: jdbc:sqlite::resource:apk.db
    driver-class-name: org.sqlite.JDBC

#电信apk文件存放路径
apkconfig:
  ######电信apk解析包指定目录
  filepath: 'd:\apk\'
  ######下载APK指定保存目录
  downloadpath: 'd:\apkdownload\'
  #####限定下载文件大小
  filemax: 104857600
  #####默认每批次启动线程数
  maxthread: 10

#app服务器接口地址
appserver:
  httpUrl: 'http://127.0.0.1:8000'

logging:
  config: classpath:logback-spring.xml

